{
pagination: {
limit: 25,
offset: 0,
count: 25,
total: 10000
},
data: [
{
author: "Evan Webeck",
title: "Steph Curry will play vs. Pacers, and Steve Kerr says Warriors never considered any other option",
description: "But before the Golden State Warriors tipped off Monday against the Pacers, Steve Kerr refuted the notion that they ever considered resting Steph Curry, despite reports to the contrary.",
url: "https://www.paradisepost.com/2021/12/13/steph-curry-will-play-vs-pacers-and-steve-kerr-says-warriors-never-considered-any-other-option/",
source: "paradisepost",
image: "https://www.paradisepost.com/wp-content/uploads/2021/12/Warriors-76ers-Basketball-1.jpg?w=1400px&strip=all",
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T18:32:57+00:00"
},
{
author: "Manuel",
title: "EEUU: Revelan plan de golpe de estado en asalto al Capitolio",
description: "Imagen principal:&nbsp;Declarar un estado de emergencia nacional para evitar la certificación de la victoria electoral de Joe Biden en el Senado y mantener a Donald Trump en el poder, esa era la estrategia del asalto al Capitolio de Estados Unidos en enero pasado.   En vísperas del dramático asalto al Congreso del 6 de enero, se estaba gestando un plan detallado para anular el resultado de las elecciones presidenciales por los pasillos del Capitolio y, quizás, la Casa Blanca.   ",
url: "http://cubasi.cu/en/node/205669",
source: "CubaSi.cu",
image: null,
category: "general",
language: "en",
country: "cu",
published_at: "2021-12-13T18:35:38+00:00"
},
{
author: "Evan Webeck",
title: "Steph Curry will play vs. Pacers, and Steve Kerr says Warriors never considered any other option",
description: "But before the Golden State Warriors tipped off Monday against the Pacers, Steve Kerr refuted the notion that they ever considered resting Steph Curry, despite reports to the contrary.",
url: "https://www.orovillemr.com/2021/12/13/steph-curry-will-play-vs-pacers-and-steve-kerr-says-warriors-never-considered-any-other-option/",
source: "orovillemr",
image: "https://www.orovillemr.com/wp-content/uploads/2021/12/Warriors-76ers-Basketball-1.jpg?w=1400px&strip=all",
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T18:32:57+00:00"
},
{
author: "Taylor Blewett",
title: "Stittsville school closed, into isolation due to COVID-19 spread with Omicron suspected",
description: "A Stittsville elementary school has been closed and all students and staff instructed to isolate after testing showed a likelihood that the Omicron variant is behind the outbreak. In a Saturday letter to families and staff at Saint-Jean-Paul II Catholic Elementary School, Ottawa Public Health advised that the whole school had been closed &#8220;as spread of [&#8230;]",
url: "https://ottawacitizen.com/news/local-news/stittsville-school-closed-into-isolation-due-to-covid-19-spread-with-omicron-suspected",
source: "Ottawa Citizen",
image: null,
category: "general",
language: "en",
country: "ca",
published_at: "2021-12-13T18:27:26+00:00"
},
{
author: "Scott Sturkol",
title: "Photo Essay: Construction of fiscal year 2020-funded barracks project continues at Fort McCoy",
description: "Construction work is shown Dec. 2 and 13, 2021, in the 1600 block of the cantonment area at Fort McCoy, Wis., for a second new barracks project on the post.",
url: "https://www.dvidshub.net/news/411006/photo-essay-construction-fiscal-year-2020-funded-barracks-project-continues-fort-mccoy",
source: "dvidshub",
image: "https://cdn.dvidshub.net/media/thumbs/photos/2112/6977054/250x155_q75.jpg",
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T18:26:53+00:00"
},
{
author: "Brian Rokos",
title: "Border agent seriously injured near Temecula by drunken driver from San Bernardino, CHP says",
description: "The collision happened at 2:22 a.m. in a northbound lane of a checkpoint on I-15, north of Rainbow Valley Road.",
url: "https://www.sbsun.com/2021/12/13/border-agent-seriously-injured-near-temecula-by-drunken-driver-from-san-bernardino-chp-says/",
source: "sbsun",
image: "https://www.sbsun.com/wp-content/uploads/2021/12/breaking_news_06-1.jpg?w=1400px&strip=all",
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T18:29:47+00:00"
},
{
author: "Avery Thompson",
title: "Paris Winningham: 5 Things To Know About The Navy Veteran Who Is A Finalist On ‘The Voice’",
description: "Paris Winningham is one of the top 5 finalists of 'The Voice' season 21. Get to know the singer as the finale gets underway.",
url: "https://hollywoodlife.com/feature/who-is-paris-winningham-the-voice-4601717/",
source: "hollywoodlife",
image: "https://hollywoodlife.com/wp-content/uploads/2021/12/Paris-Winningham-The-Voice-5-Things-NBC-ftr.jpg",
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T18:27:09+00:00"
},
{
author: "",
title: "Ontario college faculty give 5 days’ notice of possible labour action",
description: "The Ontario Public Service Employees Union says it gave the College Employer Council five days' notice that its members could begin working to rule.",
url: "https://globalnews.ca/news/8447059/ontario-college-faculty-possible-labour-action/",
source: "chbcnews",
image: null,
category: "general",
language: "en",
country: "ca",
published_at: "2021-12-13T18:35:15+00:00"
},
{
author: null,
title: "Art Vivant Is The Rare Play On Possibly The Best Asset Class",
description: "Art Vivant Is The Rare Play On Possibly The Best Asset Class",
url: "https://seekingalpha.com/article/4474953-art-vivant-is-the-rare-play-on-possibly-the-best-asset-class?source=feed_all_articles",
source: "Seeking Alpha",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T18:30:38+00:00"
},
{
author: null,
title: "Windies fall to Pakistan in first T20I",
description: "......",
url: "https://www.nationnews.com/2021/12/13/windies-fall-pakistan-first-t20i/",
source: "Nation News",
image: null,
category: "general",
language: "en",
country: "bb",
published_at: "2021-12-13T18:31:17+00:00"
},
{
author: null,
title: "New Edition Announces The Culture Tour Beginning February 2022 With Charlie Wilson and Special Guest Jodeci",
description: "(marketscreener.com) Veteran R&amp;B group New Edition headlines an iconic lineup with the legendary Charlie Wilson, along with special guest, Jodeci, the bad boys of R&amp;B. The Culture Tour kicks off a 30-city tour February 2022, in Columbus, Ga., with stops in Los Angeles, New York, and New Edition&rsquo;s hometown of Boston.This press release features...https://www.marketscreener.com/news/latest/New-Edition-Announces-The-Culture-Tour-Beginning-February-2022-With-Charlie-Wilson-and-Special-Guest--37306970/?utm_medium=RSS&utm_content=20211213",
url: "https://www.marketscreener.com/news/latest/New-Edition-Announces-The-Culture-Tour-Beginning-February-2022-With-Charlie-Wilson-and-Special-Guest--37306970/?utm_medium=RSS&utm_content=20211213",
source: "4-traders",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:09:01+00:00"
},
{
author: null,
title: "Cowen : Tech-Enabled Coaching Is Fueling Investment in Professional Development in Higher Education",
description: "(marketscreener.com) By Alex Hicks Coaching services providers in education and business are growing fast and attracting unusually rich valuations for tech-enabled services. What do you remember from the last time you had a training day or had to complete an online learning module for work? If you're like most people, the honest...https://www.marketscreener.com/quote/stock/COWEN-INC-32134081/news/Cowen-Tech-Enabled-Coaching-Is-Fueling-Investment-in-Professional-Development-in-Higher-Education-37306961/?utm_medium=RSS&utm_content=20211213",
url: "https://www.marketscreener.com/quote/stock/COWEN-INC-32134081/news/Cowen-Tech-Enabled-Coaching-Is-Fueling-Investment-in-Professional-Development-in-Higher-Education-37306961/?utm_medium=RSS&utm_content=20211213",
source: "4-traders",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:06:04+00:00"
},
{
author: null,
title: "Compound Semiconductor: Navitas Plans For GaN Dominance",
description: "(marketscreener.com) Recent analysis indicates that Navitas is now the market leader of GaN power devices. Rebecca Pool talks to Stephen Oliver, Vice President of Investor Relations, about the company's progress, products and plans. Image: Stephen Oliver with Dan Kinzer, Co-Founder and Chief Technology Officer/Chief Operating Officer ,...https://www.marketscreener.com/quote/stock/NAVITAS-SEMICONDUCTOR-COR-128455151/news/Compound-Semiconductor-Navitas-Plans-For-GaN-Dominance-37306960/?utm_medium=RSS&utm_content=20211213",
url: "https://www.marketscreener.com/quote/stock/NAVITAS-SEMICONDUCTOR-COR-128455151/news/Compound-Semiconductor-Navitas-Plans-For-GaN-Dominance-37306960/?utm_medium=RSS&utm_content=20211213",
source: "4-traders",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:06:04+00:00"
},
{
author: "ABMN Staff",
title: "Phoenix Holdings Ltd. Grows Stock Holdings in PayPal Holdings, Inc. (NASDAQ:PYPL)",
description: "Phoenix Holdings Ltd. Grows Stock Holdings in PayPal Holdings, Inc. (NASDAQ:PYPL)",
url: "https://www.americanbankingnews.com/2021/12/13/phoenix-holdings-ltd-grows-stock-holdings-in-paypal-holdings-inc-nasdaqpypl.html",
source: "americanbankingnews",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:10:45+00:00"
},
{
author: "ABMN Staff",
title: "Fiduciary Group LLC Has $14.06 Million Stock Position in Union Pacific Co. (NYSE:UNP)",
description: "Fiduciary Group LLC Has $14.06 Million Stock Position in Union Pacific Co. (NYSE:UNP)",
url: "https://www.americanbankingnews.com/2021/12/13/fiduciary-group-llc-has-14-06-million-stock-position-in-union-pacific-co-nyseunp.html",
source: "americanbankingnews",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:10:45+00:00"
},
{
author: "ABMN Staff",
title: "iShares S&#038;P SmallCap 600 ETF (NYSEARCA:IJR) is LVZ Inc.&#8217;s 3rd Largest Position",
description: "iShares S&#038;P SmallCap 600 ETF (NYSEARCA:IJR) is LVZ Inc.&#8217;s 3rd Largest Position",
url: "https://www.americanbankingnews.com/2021/12/13/ishares-sp-smallcap-600-etf-nysearcaijr-is-lvz-inc-s-3rd-largest-position.html",
source: "americanbankingnews",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:10:44+00:00"
},
{
author: "ABMN Staff",
title: "Aemetis (NASDAQ:AMTX) Trading Down 6.3%",
description: "Aemetis (NASDAQ:AMTX) Trading Down 6.3%",
url: "https://www.americanbankingnews.com/2021/12/13/aemetis-nasdaqamtx-trading-down-6-3.html",
source: "americanbankingnews",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:08:42+00:00"
},
{
author: "ABMN Staff",
title: "Robert P. Fisher, Jr. Buys 5,000 Shares of Cleveland-Cliffs Inc. (NYSE:CLF) Stock",
description: "Robert P. Fisher, Jr. Buys 5,000 Shares of Cleveland-Cliffs Inc. (NYSE:CLF) Stock",
url: "https://www.americanbankingnews.com/2021/12/13/robert-p-fisher-jr-buys-5000-shares-of-cleveland-cliffs-inc-nyseclf-stock.html",
source: "americanbankingnews",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:06:43+00:00"
},
{
author: "ABMN Staff",
title: "Arqit Quantum (NASDAQ:ARQQ) Stock Price Down 8.9%",
description: "Arqit Quantum (NASDAQ:ARQQ) Stock Price Down 8.9%",
url: "https://www.americanbankingnews.com/2021/12/13/arqit-quantum-nasdaqarqq-stock-price-down-8-9.html",
source: "americanbankingnews",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:06:43+00:00"
},
{
author: "Chris Smith",
title: "macOS Monterey 12.1 adds SharePlay, Apple Music Voice Plan and fixes MBP charging",
description: "macOS Monterey 12.1 Features: Apple has launched the first major update for macOS Monterey, bringing the SharePlay &#8216;watch party&#8217; feature and an important fix for MacBook Pro 2021 owners. The update, which is available to download now (via Apple logo > About This Mac > Software Update), is headlined by the addition to FaceTime, which [&#8230;]The post macOS Monterey 12.1 adds SharePlay, Apple Music Voice Plan and fixes MBP charging appeared first on Trusted Reviews.",
url: "https://www.trustedreviews.com/news/macos-monterey-12-1-adds-shareplay-apple-music-voice-plan-and-fixes-mbp-charging-4190939?utm_source=keystone&utm_medium=keystone_core_reviews_rss&utm_campaign=trusted+reviews",
source: "theinquirer",
image: "https://www.trustedreviews.com/wp-content/uploads/sites/54/2021/06/WWDC-21-Mac-OS-Monterey-3-1024x576.png",
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:05:38+00:00"
},
{
author: "Sunday Ejike - Abuja",
title: "Body of SAN knocks Appeal Court for refusing to rule on ex-CJN, Onnoghen’s matter over suspension",
description: "Tribune OnlineBody of SAN knocks Appeal Court for refusing to rule on ex-CJN, Onnoghen&#8217;s matter over suspensionThe Body of Senior Advocates of Nigeria (BOSAN) on Monday slammed the Court of Appeal for refusing to deliver a ruling on a suit brought before it by a former Chief Justice of Nigeria (CJN), Justice Walter Onnoghen. Speaking at a valedictory court session in honour of a former Chief Judge of the Federal High [&#8230;]Body of SAN knocks Appeal Court for refusing to rule on ex-CJN, Onnoghen&#8217;s matter over suspensionTribune Online",
url: "https://tribuneonlineng.com/body-of-san-knocks-appeal-court-for-refusing-to-rule-on-ex-cjn-onnoghens-matter-over-suspension/",
source: "tribune",
image: null,
category: "general",
language: "en",
country: "ng",
published_at: "2021-12-13T19:02:58+00:00"
},
{
author: "The Associated Press",
title: "Pope says he’ll meet with French sex abuse commission",
description: "By NICOLE WINFIELD Associated Press ROME (AP) — Pope Francis has agreed to meet with the commission that published a ground-breaking report into clergy sexual abuse in the French Catholic Church. That&#8217;s according to French bishops who met with him. The president of the French Bishops Conference told reporters Monday that Francis had agreed “inThe post Pope says he&#8217;ll meet with French sex abuse commission appeared first on KYMA.",
url: "https://kyma.com/news/ap-national/2021/12/13/pope-says-hell-meet-with-french-sex-abuse-commission/",
source: "kyma",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:05:37+00:00"
},
{
author: "Matt Kelley",
title: "Iowa Red Cross volunteers head south to help with tornado recovery",
description: "Iowa volunteers with the American Red Cross are already providing help in the South after weekend storms spun off at least 50 tornadoes in eight states. Josh Murray, a spokesman for the Iowa-Nebraska region of the Red Cross, says most of the Iowans are now in western Kentucky, where the damage is extreme and one [&#8230;]",
url: "https://www.radioiowa.com/2021/12/13/iowa-red-cross-volunteers-head-south-to-help-with-tornado-recovery/",
source: "radioiowa",
image: null,
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:07:58+00:00"
},
{
author: "laurie-churchman-met",
title: "Woman jailed after abusing boy, 7, on webcam for online paedophiles",
description: "Astrid Hilton filmed herself sexually abusing a seven-year-old boy for the pleasure of online predators.",
url: "https://metro.co.uk/2021/12/13/woman-jailed-after-abusing-boy-7-on-webcam-for-online-paedophiles-15764336/",
source: "Metro",
image: "https://metro.co.uk/wp-content/uploads/2021/12/PRC_214958643.jpg?quality=90&strip=all",
category: "general",
language: "en",
country: "gb",
published_at: "2021-12-13T19:08:08+00:00"
},
{
author: "wtopstaff",
title: "Manchin: Democrats should prioritize, curb cost of $2T bill",
description: "WASHINGTON (AP) — Democrats should curb the cost of their $2 trillion social and environment bill by choosing their top&#8230;",
url: "https://wtop.com/national/2021/12/manchin-democrats-should-prioritize-curb-cost-of-2t-bill/",
source: "wtop",
image: "https://wtop.com/wp-content/uploads/2021/12/Congress_Budget_71943-1024x715.jpg",
category: "general",
language: "en",
country: "us",
published_at: "2021-12-13T19:05:49+00:00"
}
]
}